from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QGridLayout

#from main import dbs


class SecondWindow(QtWidgets.QWidget):
    def __init__(self,
                 parent=None):  # если собрался передавать аргументы, то не забудь их принять (nameofargument, self, parent=None)
        super().__init__(parent, QtCore.Qt.Window)
        self.build()  # ну и передать в открывающееся окно соответственно (nameofargument, self)

    def build(self):
        self.setGeometry(300, 300, 300, 300)
        self.setWindowTitle('NoTittle')
        self.combobox = QtWidgets.QComboBox(self)
        self.combobox.setObjectName("comboBox")
        self.combobox.addItems(dbs)
        """self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("b_ok")
        self.pushButton.setText("jgf")
        self.pushButton."""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 210)
        MainWindow.setMinimumSize(QtCore.QSize(550, 210))
        MainWindow.setMaximumSize(QtCore.QSize(550, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1c.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.l_base = QtWidgets.QLineEdit(self.centralwidget)
        self.l_base.setObjectName("l_base")
        self.gridLayout.addWidget(self.l_base, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.b_exit = QtWidgets.QPushButton(self.centralwidget)
        self.b_exit.setObjectName("b_exit")
        self.gridLayout.addWidget(self.b_exit, 1, 4, 1, 1)
        self.l_out = QtWidgets.QLineEdit(self.centralwidget)
        self.l_out.setObjectName("l_out")
        self.gridLayout.addWidget(self.l_out, 2, 1, 1, 1)
        self.b_out_select = QtWidgets.QToolButton(self.centralwidget)
        self.b_out_select.setObjectName("b_out_select")
        self.gridLayout.addWidget(self.b_out_select, 2, 2, 1, 1)
        self.b_bd_select = QtWidgets.QToolButton(self.centralwidget)
        self.b_bd_select.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.b_bd_select.setObjectName("b_bd_select")
        self.gridLayout.addWidget(self.b_bd_select, 0, 2, 1, 1)
        self.d_date = QtWidgets.QDateEdit(self.centralwidget)
        self.d_date.setAcceptDrops(False)
        self.d_date.setCalendarPopup(True)
        self.d_date.setObjectName("d_date")
        self.gridLayout.addWidget(self.d_date, 1, 1, 1, 1)
        self.l_bd_num = QtWidgets.QLineEdit(self.centralwidget)
        self.l_bd_num.setObjectName("l_bd_num")
        self.gridLayout.addWidget(self.l_bd_num, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 240, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.c_xls = QtWidgets.QCheckBox(self.layoutWidget)
        self.c_xls.setObjectName("c_xls")
        self.horizontalLayout.addWidget(self.c_xls)
        self.c_xlsx = QtWidgets.QCheckBox(self.layoutWidget)
        self.c_xlsx.setObjectName("c_xlsx")
        self.horizontalLayout.addWidget(self.c_xlsx)
        self.c_dash = QtWidgets.QCheckBox(self.layoutWidget)
        self.c_dash.setObjectName("c_dash")
        self.horizontalLayout.addWidget(self.c_dash)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 2, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.b_run = QtWidgets.QPushButton(self.centralwidget)
        self.b_run.setObjectName("b_run")
        self.gridLayout.addWidget(self.b_run, 0, 4, 1, 1)
        self.b_find = QtWidgets.QToolButton(self.centralwidget)
        self.b_find.setObjectName("b_find")
        self.b_find.hide()
        self.gridLayout.addWidget(self.b_find, 0, 3, 1, 1)
        self.b_save = QtWidgets.QPushButton(self.centralwidget)
        self.b_save.setObjectName("b_save")
        self.gridLayout.addWidget(self.b_save, 5, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.statusbar.hide()
        MainWindow.setWindowTitle(_translate("MainWindow", "TMR-Tracker(5.3.0.486) 1C Report engine (2022-06-21.RC GUI)"))
        self.label_3.setText(_translate("MainWindow", "Путь выгрузки:"))
        self.label_2.setText(_translate("MainWindow", "Дата:"))
        self.b_exit.setText(_translate("MainWindow", "Выход"))
        self.b_out_select.setText(_translate("MainWindow", "..."))
        self.b_bd_select.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки:"))
        self.c_xls.setText(_translate("MainWindow", "XLS"))
        self.c_xlsx.setText(_translate("MainWindow", "XLSX"))
        self.c_dash.setText(_translate("MainWindow", "Убрать (-)"))
        self.label_4.setText(_translate("MainWindow", "Номер Фермы:"))
        self.label.setText(_translate("MainWindow", "База:"))
        self.b_run.setText(_translate("MainWindow", "Выгрузить"))
        self.b_find.setText(_translate("MainWindow", "Найти"))
        self.b_save.setText(_translate("MainWindow", "Сохранить настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
