SELECT 
	(SELECT FARMNUMBER FROM BEDRIJF), 
	(SELECT NAMEFARMER FROM BEDRIJF), 
	CAST(DELIVERED_TIME AS DATE),
	DS_RATION.DISPLAY_NAME, 
	DS_RATION.DESCRIPTION, 
	DS_GROUP.DISPLAY_NAME,
	DS_GROUP.DESCRIPTION,
	(SELECT DS_GROUP_TYPE.NAME FROM DS_GROUP_TYPE WHERE DS_GROUP_TYPE.ID = DS_GROUP.GROUP_TYPE), 
	DS_BATCH_DELIVERY.HEAD_COUNT,
	DS_INGREDIENT.DISPLAY_NAME,
	DS_INGREDIENT.DESCRIPTION,
	ROUND(DS_BATCH_LOAD.CALL_WEIGHT/DS_BATCH_DELIVERY.HEAD_COUNT,2), 
	ROUND(DS_BATCH_LOAD.LOADED_WEIGHT/DS_BATCH_DELIVERY.HEAD_COUNT,2),
	DS_BATCH_LOAD.CALL_WEIGHT, 
	DS_BATCH_LOAD.LOADED_WEIGHT,
	ROUND(DS_BATCH_LOAD.LOADED_WEIGHT*(DS_BATCH_DELIVERY.DELIVERED_WEIGHT/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0)),2),
	ROUND(DS_BATCH_LOAD.CALL_WEIGHT*DRYMATTER_PERC/100/DS_BATCH_DELIVERY.HEAD_COUNT,2), 
	ROUND(DS_BATCH_LOAD.LOADED_WEIGHT*DRYMATTER_PERC/100/DS_BATCH_DELIVERY.HEAD_COUNT,2), 
	ROUND(DS_BATCH_LOAD.CALL_WEIGHT*DRYMATTER_PERC/100,2), 
	ROUND(DS_BATCH_LOAD.LOADED_WEIGHT*DRYMATTER_PERC/100,2), 
	ROUND(DS_BATCH_LOAD.LOADED_WEIGHT*(DS_BATCH_DELIVERY.DELIVERED_WEIGHT/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0))*DS_BATCH_LOAD.DRYMATTER_PERC/100,2),
	ROUND((DS_BATCH_LOAD.LOADED_WEIGHT*((DS_BATCH_DELIVERY.DELIVERED_WEIGHT-DS_BATCH_DELIVERY.WEIGHBACK_AMOUNT)/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0))*DS_BATCH_LOAD.DRYMATTER_PERC/100)/DS_BATCH_DELIVERY.HEAD_COUNT,2)
FROM DS_BATCH
INNER JOIN DS_RATION ON DS_RATION.ID = DS_BATCH.RATION_ID  
INNER JOIN DS_BATCH_LOAD ON DS_BATCH_LOAD.BATCH_ID  = DS_BATCH.id
INNER JOIN DS_BATCH_DELIVERY ON DS_BATCH_DELIVERY.BATCH_ID  = DS_BATCH.id
INNER JOIN DS_GROUP ON DS_GROUP.ID = DS_BATCH_DELIVERY.GROUP_ID 
INNER JOIN DS_INGREDIENT ON DS_INGREDIENT.ID = DS_BATCH_load.INGREDIENT_ID
WHERE CAST(DELIVERED_TIME AS DATE) = '2022-02-02' 
