SELECT 
	(SELECT FARMNUMBER FROM BEDRIJF), 
	(SELECT NAMEFARMER FROM BEDRIJF), 
	CAST(dbl.LOADED_TIME  AS DATE) cs,
	di.DISPLAY_NAME di, 
	di.DESCRIPTION ds,
	sum(dbl.LOADED_WEIGHT) ss,
	Round(sum(dbl.LOADED_WEIGHT*dbl.DRYMATTER_PERC/100),0) sss
FROM DS_BATCH_LOAD dbl 
INNER JOIN DS_INGREDIENT di ON di.ID = dbl.INGREDIENT_ID 
WHERE CAST(dbl.LOADED_TIME  AS DATE) = '2022-02-01'
GROUP BY cs, di, ds