SELECT 
	--Ферма №
	(SELECT	FARMNUMBER FROM	BEDRIJF), 
	--Название фермы
	(SELECT	NAMEFARMER FROM	BEDRIJF),
	--Дата Партии
	CAST(DELIVERED_TIME AS DATE),
	--Имя рациона
	DS_RATION.DISPLAY_NAME,
	--Рацион
	DS_RATION.DESCRIPTION,
	--Группа
	DS_GROUP.DESCRIPTION,
	--Тип группы
	(SELECT	DS_GROUP_TYPE.NAME FROM DS_GROUP_TYPE WHERE DS_GROUP_TYPE.ID = DS_GROUP.GROUP_TYPE), 
	--Поголовье
	DS_BATCH_DELIVERY.HEAD_COUNT HCD,
	--ИнгредиентыID
	DS_INGREDIENT.EXTERNAL_ID,
	--Ингредиент
	DS_INGREDIENT.DESCRIPTION dsID,
	--Требуем. вес/голову
	round(DS_BATCH_LOAD.CALL_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)/NULLIF(DS_BATCH_delivery.HEAD_COUNT,0),2),
	--Загруженный вес/Голову
	round(DS_BATCH_LOAD.LOADED_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)/NULLIF(DS_BATCH_delivery.HEAD_COUNT,0),2),
	--Требуем.вес
	round(DS_BATCH_LOAD.CALL_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id),2),
	--Загруженный вес
	round(DS_BATCH_LOAD.LOADED_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id),2),
	--Розданный вес
	round(DS_BATCH_LOAD.LOADED_WEIGHT*(DS_BATCH_DELIVERY.DELIVERED_WEIGHT/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0))/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id),2),
	--Треб. сух. вес/голову
	round(DS_BATCH_LOAD.CALL_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)/NULLIF(DS_BATCH_delivery.HEAD_COUNT,0)*DS_BATCH_LOAD.DRYMATTER_PERC / 100,2),
	--Загруженный сух. вес/голову
	round(DS_BATCH_LOAD.LOADED_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)/NULLIF(DS_BATCH_delivery.HEAD_COUNT,0)*DS_BATCH_LOAD.DRYMATTER_PERC / 100,2),
	--Треб. сух. вес
	round(DS_BATCH_LOAD.CALL_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)*DS_BATCH_LOAD.DRYMATTER_PERC / 100,2),
	--Загруженный сух. вес
	round(DS_BATCH_LOAD.LOADED_WEIGHT/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)*DS_BATCH_LOAD.DRYMATTER_PERC / 100,2),
	--Розданный сух. вес
	round(DS_BATCH_LOAD.LOADED_WEIGHT*(DS_BATCH_DELIVERY.DELIVERED_WEIGHT/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0))/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)*DS_BATCH_LOAD.DRYMATTER_PERC / 100,2),
	--Потребление сухого вещества / голову
	round(DS_BATCH_LOAD.LOADED_WEIGHT*((DS_BATCH_DELIVERY.DELIVERED_WEIGHT-DS_BATCH_DELIVERY.WEIGHBACK_AMOUNT)/NULLIF(DS_BATCH_DELIVERY.CALL_WEIGHT,0))/(SELECT NULLIF(sum(DS_BATCH_LOAD.LOADED_WEIGHT),0)/NULLIF(DS_BATCH_delivery.CALL_WEIGHT,0) FROM DS_BATCH_LOAD WHERE DS_BATCH_LOAD.BATCH_ID = DS_BATCH.id)*(DS_BATCH_LOAD.DRYMATTER_PERC / 100)/NULLIF(DS_BATCH_delivery.HEAD_COUNT,0),2),
	--Надои
	(SELECT ROUND(avg(DS_MILK.AMOUNT),0) FROM DS_MILK WHERE DS_MILK.GROUP_ID=DS_BATCH_DELIVERY.GROUP_ID AND CAST(ds_milk.MILK_DATE AS date) = '2022-06-12')
FROM DS_BATCH
INNER JOIN DS_RATION ON	DS_RATION.ID = DS_BATCH.RATION_ID
INNER JOIN DS_BATCH_LOAD ON	DS_BATCH_LOAD.BATCH_ID = DS_BATCH.ID
INNER JOIN DS_BATCH_DELIVERY ON	DS_BATCH_DELIVERY.BATCH_ID = DS_BATCH.ID 
INNER JOIN DS_GROUP ON	DS_GROUP.ID = DS_BATCH_DELIVERY.GROUP_ID 
INNER JOIN DS_INGREDIENT ON	DS_INGREDIENT.ID = DS_BATCH_LOAD.INGREDIENT_ID
WHERE CAST(DELIVERED_TIME AS DATE) = '2022-06-12'
	